# Generated by Django 3.2.6 on 2021-08-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.IntegerField()),
                ('EmpName', models.TextField(max_length=50)),
                ('EmpSalary', models.FloatField(max_length=15)),
            ],
        ),
    ]
