# Generated by Django 3.2.6 on 2021-08-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='EmpCity',
            field=models.TextField(default='mumbai'),
        ),
    ]
