# Generated by Django 3.2.6 on 2021-08-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ermsapp', '0002_employee_empcity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpCity',
            field=models.TextField(default='Mumbai'),
        ),
    ]
