# Generated by Django 3.2.6 on 2021-09-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ermsapp', '0003_alter_employee_empcity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='EmpCity',
            new_name='EmpTeam',
        ),
    ]
